Final-Year-Project-master/chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    # this url is for each unique rooms
    path('<str:room>', views.room, name='room'),
    # this url for a view that will show all the messagaes to the room
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

Final-Year-Project-master/looknearby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentications/', include("authentications.urls")),
    path('', include("helloapp.urls")),
    path('chat/', include("chat.urls")),
]



if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
  

chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    # this url is for each unique rooms
    path('<str:room>', views.room, name='room'),
    # this url for a view that will show all the messagaes to the room
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

looknearby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentications/', include("authentications.urls")),
    path('', include("helloapp.urls")),
    path('chat/', include("chat.urls")),
]



if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
  

Final-Year-Project-master/chat/models.py
from django.db import models
from datetime import datetime

# this is a room model, here all names of the room should be unique.
class Room(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name



# this is message view, in this database we will store all the messages with some basic details.
class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)

    def __str__(self):
        return self.room

chat/models.py
from django.db import models
from datetime import datetime

# this is a room model, here all names of the room should be unique.
class Room(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return self.name



# this is message view, in this database we will store all the messages with some basic details.
class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)

    def __str__(self):
        return self.room

Final-Year-Project-master/chat/views.py
from django.shortcuts import redirect, render
from .models import Message
from django.http import HttpResponse, JsonResponse


# Create your views here.

# this is a unique room for two people to chat. this room is unique cause it made by two people's username
def room (request, room):
    # checking the user is authenticated or not
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    
    # if somebody wants to post any message then save the message into the database. Each message can be identify by using their room name
    if request.method == 'POST':
        message = Message()
        message.value = request.POST['message']
        message.user = request.POST['username']
        message.room = request.POST['room_id']
        message.save()

    # normally just render the simple template with a parameter room name.
    return render(request, "chat/room.html", {'room' : room})



# this view is for showing the messagaes that have been sent to the room
def getMessages(request, room):
    # checking is the user authenticated or not
    if not request.user.is_authenticated:
        return redirect('authentications:login')

    # get all the messagaes that have been sent to the specific room
    messages = Message.objects.filter(room=room)
    # get all the messages and send it back to the room templete to show the chats.
    return JsonResponse({"messages":list(messages.values())})

chat/views.py
from django.shortcuts import redirect, render
from .models import Message
from django.http import HttpResponse, JsonResponse


# Create your views here.

# this is a unique room for two people to chat. this room is unique cause it made by two people's username
def room (request, room):
    # checking the user is authenticated or not
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    
    # if somebody wants to post any message then save the message into the database. Each message can be identify by using their room name
    if request.method == 'POST':
        message = Message()
        message.value = request.POST['message']
        message.user = request.POST['username']
        message.room = request.POST['room_id']
        message.save()

    # normally just render the simple template with a parameter room name.
    return render(request, "chat/room.html", {'room' : room})



# this view is for showing the messagaes that have been sent to the room
def getMessages(request, room):
    # checking is the user authenticated or not
    if not request.user.is_authenticated:
        return redirect('authentications:login')

    # get all the messagaes that have been sent to the specific room
    messages = Message.objects.filter(room=room)
    # get all the messages and send it back to the room templete to show the chats.
    return JsonResponse({"messages":list(messages.values())})

Final-Year-Project-master/chat/templates/chat/room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- do not delete this link -->
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    <title>looknearby ⦁ messages</title>
</head>
<body>
    <!-- this is the name of the room -->
    <!-- FOR STYLE -->
    {{ room }}


    <!-- this div is for displaying all the messages -->
    <!-- FOR STYLE -->
    <div id="display"> <!-- do not change the id -->

    </div>


    <!-- do not change this script tag -->
    <script>
    $(document).ready(function(){
  
      setInterval(function(){
        $.ajax({
            type: 'GET',
            url : "{% url 'chat:getMessages' room %}",
            success: function(response){
              console.log(response);
              $("#display").empty();
              for (var key in response.messages)
              {
                  var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                  $("#display").append(temp);
              }
            },
            error: function(response){
              alert('An error occured')
            }
          });
        },1000);
      })
  </script>
  






    <!-- this div for inputting the message and send the message using the button-->
    <!-- FOR STYLE -->
    <div>
        <!-- do not change the ids -->
        <form id="post-form">
            {% csrf_token %}
            <input type="text" name="username" id="username" value="{{request.user.username}}" hidden/>
            <input type="text" name="room_id" id="room_id" value="{{room}}" hidden/>
            <input type="text" name="message" id="message" width="100px" />
            <input type="submit" value="Send">
        </form>

    </div>


    
    <!-- do not change this script tag -->
    <script type="text/javascript">
        $(document).on('submit','#post-form',function(e){
          e.preventDefault();
      
          $.ajax({
            type:'POST',
            url:"{% url 'chat:room' room %}",
            data:{
                username:$('#username').val(),
                room_id:$('#room_id').val(),
                message:$('#message').val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function(data){
               //alert(data)
            }
          });
          document.getElementById('message').value = ''
        });
      </script>

</body>
</html>