Final-Year-Project-master/looknearby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentications/', include("authentications.urls")),
    path('', include("helloapp.urls")),
    path('chat/', include("chat.urls")),
]



if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
  

authentications/urls.py
from django.urls import path
from . import views


app_name = "authentications"
urlpatterns = [
    path('registration', views.registration_view, name="registration"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    # this url is for each unique rooms
    path('<str:room>', views.room, name='room'),
    # this url for a view that will show all the messagaes to the room
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

looknearby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentications/', include("authentications.urls")),
    path('', include("helloapp.urls")),
    path('chat/', include("chat.urls")),
]



if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
  

Final-Year-Project-master/authentications/models.py
from django.db import models

# Create your models here.

authentications/models.py
from django.db import models

# Create your models here.

Final-Year-Project-master/authentications/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput

class ModifiedUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'e.g. Harry', 'class' : 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'e.g. Potter', 'class' : 'form-control'}))


    password1 = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder' : 'create a password'})
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder' : 'confirm your password'})
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']
        widgets = {
            'username' : TextInput ( attrs={'placeholder':'e.g. harrypotter', 'class' : 'form-control'}),
        }

authentications/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput

class ModifiedUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'e.g. Harry', 'class' : 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'e.g. Potter', 'class' : 'form-control'}))


    password1 = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder' : 'create a password'})
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder' : 'confirm your password'})
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']
        widgets = {
            'username' : TextInput ( attrs={'placeholder':'e.g. harrypotter', 'class' : 'form-control'}),
        }

Final-Year-Project-master/authentications/views.py
import profile
from django.shortcuts import render, redirect
from .forms import ModifiedUserCreationForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from helloapp.models import Profile, Location
from django.contrib.auth.models import User


# Create your views here.
def registration_view(request):
    if request.method == 'POST':
        form = ModifiedUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            profile = Profile()
            location = Location()
            profile.user = User.objects.get(username=username)
            location.user = User.objects.get(username=username)
            location.save()
            profile.save()
            messages.success(request, f"{username} is successfully registered!")
            return redirect('authentications:login')
        else:
            username = form.cleaned_data.get('username')
            messages.error(request, f"somthing worng with {username} user!")
            return render(request, "authentications/registration.html", 
                {"form" : form}
            )
    else:
        form = ModifiedUserCreationForm()
        return render(request, "authentications/registration.html", 
            {"form" : form}
        )





def login_view(request):
    if request.user.is_authenticated:
        return redirect("helloapp:index")
    else:
        if request.method == 'POST':
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"{username} is successfully logged in")
                return redirect('helloapp:index')
            else:
                messages.error(request, f"{username} is not varified!")
                return render(request, "authentications/login.html")
        else:
            return render(request, "authentications/login.html")





def logout_view(request):
    username = request.user.username
    logout(request) 
    messages.success(request, f"{username} is successfully logged out!")
    return redirect('authentications:login')

authentications/views.py
import profile
from django.shortcuts import render, redirect
from .forms import ModifiedUserCreationForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from helloapp.models import Profile, Location
from django.contrib.auth.models import User


# Create your views here.
def registration_view(request):
    if request.method == 'POST':
        form = ModifiedUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            profile = Profile()
            location = Location()
            profile.user = User.objects.get(username=username)
            location.user = User.objects.get(username=username)
            location.save()
            profile.save()
            messages.success(request, f"{username} is successfully registered!")
            return redirect('authentications:login')
        else:
            username = form.cleaned_data.get('username')
            messages.error(request, f"somthing worng with {username} user!")
            return render(request, "authentications/registration.html", 
                {"form" : form}
            )
    else:
        form = ModifiedUserCreationForm()
        return render(request, "authentications/registration.html", 
            {"form" : form}
        )





def login_view(request):
    if request.user.is_authenticated:
        return redirect("helloapp:index")
    else:
        if request.method == 'POST':
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"{username} is successfully logged in")
                return redirect('helloapp:index')
            else:
                messages.error(request, f"{username} is not varified!")
                return render(request, "authentications/login.html")
        else:
            return render(request, "authentications/login.html")





def logout_view(request):
    username = request.user.username
    logout(request) 
    messages.success(request, f"{username} is successfully logged out!")
    return redirect('authentications:login')

authentications/templates/authentications/layout.html
{% load static %}


<!-- THIS IS LAYOUT FILE DON'T NEED TO STYLE. IF YOU ARE USING CSS OR BOOTSTRAP OR JAVASCRIPT THEN IMPORT ALL THE LINKS HERE -->

<!DOCTYPE html>
<html lang="en">
<head>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static './authentications/style.css' %}">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    
    <h1 align="center">LookNearBy</h1>
    <div id="body-content">
        <div>
        </div>
        {% block body %} {% endblock %}
    </div>

</body>
</html>

authentications/templates/authentications/login.html
{% extends "authentications/layout.html" %}
{% load static %}
{% block title %}login ⦁ looknearby{% endblock %}

{% block body %}

    <!-- FOR STYLE -->
    {% if messages %}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{message}}
            {% endfor %}
        </div>
    {% endif %}

    <!-- FOR STYLE -->
    <h2 style="color: #084594;" class="display-5">Login page</h2>
    

    <!-- FOR STYLE -->
    <form action="{% url "authentications:login" %}" method="post">
        {% csrf_token %}
        <br>
        <div class="mb-3">
        <div>
        <label for="username" class="form-label">Username:</label>
        </div>
        <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="mb-3">
        <div>
        <label for="password" class="form-label">Password:</label>
        </div>
        <input type="password" name="password" id="password" aria-describedby="passwordHelp" class="form-control">

        <input type="submit" value="Login" class="btn btn-outline-primary">
        
        <ul>
      <li> 
           <div id="passwordHelp" class="form-text"> <u>Do not share your password with anyone! </u></div>
      </ul>
   
        </div>
    
  
   
   
    </form>

    <!-- FOR STYLE -->
    {% if request.user.username %} 
        <button>
            <a href="{% url "authentications:logout" %}">Logout</a>
        </button>
    {% endif %}

    <!-- FOR STYLE -->
    <p class="lead">
        hey! don't have an account? then <a class="link-primary" href="{% url "authentications:registration" %}"> <i> <b>Register</b></i></a> Yourself.
    </p>
{% endblock %}

authentications/templates/authentications/registration.html
{% extends "authentications/layout.html" %}

{% block title %}registration ⦁ Looknearby{% endblock %}
>
{% block body %}
    <!-- FOR STYLE -->

    <h2 class="display-5">Registration Form</h2>

    <!-- FOR STYLE -->
    <form action="{% url "authentications:registration" %}" method="post">
    
        {% csrf_token %}
        <div class="mb-3">
            {{ form.first_name.label }}
            {{ form.first_name }}
        </div>
    
        <div class="mb-3">
            {{ form.last_name.label }}
            {{ form.last_name }}
        </div>
    
        <div class="mb-3">
            {{ form.username.label }}
            {{  form.username }}
        </div>
    
        <div class="mb-3">
            {{ form.password1.label }}
            {{ form.password1 }}
        </div>
    
        <div class="mb-3">
            {{ form.password2.label }}
            {{ form.password2 }}
        </div>
    


     
        <input type="submit" value="Register" class="btn btn-outline-primary" >

    </form>

    <!-- FOR STYLE -->
    <p class="lead">
        Hey! already have an account?  Then <a href="{% url "authentications:login" %}" ><b><i>Login</i></b> </a>  Yourself.
    </p>
{% endblock %}