Final-Year-Project-master/helloapp/urls.py
from django.urls import path
from . import views

app_name = 'helloapp'
urlpatterns = [
    path('', views.index_view, name="index"),
    path('profile', views.profile_view, name="profile"),
    path('<str:username>', views.user_details_view, name="user_details"),
]

authentications/urls.py
from django.urls import path
from . import views


app_name = "authentications"
urlpatterns = [
    path('registration', views.registration_view, name="registration"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    # this url is for each unique rooms
    path('<str:room>', views.room, name='room'),
    # this url for a view that will show all the messagaes to the room
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

helloapp/urls.py
from django.urls import path
from . import views

app_name = 'helloapp'
urlpatterns = [
    path('', views.index_view, name="index"),
    path('profile', views.profile_view, name="profile"),
    path('<str:username>', views.user_details_view, name="user_details"),
]

looknearby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentications/', include("authentications.urls")),
    path('', include("helloapp.urls")),
    path('chat/', include("chat.urls")),
]



if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
  

Final-Year-Project-master/helloapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="profile")
    profile_picture = models.FileField()
    bio = models.CharField(max_length=256)
    gender = models.CharField(max_length=10)
    relationship = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username}"



class Location(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="location", primary_key=True)
    longitude = models.FloatField(default=0.0)
    latitude = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.user.username}"





class Friend(models.Model):
    sender = models.TextField(max_length=20)
    receiver = models.TextField(max_length=20)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.sender}"

helloapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="profile")
    profile_picture = models.FileField()
    bio = models.CharField(max_length=256)
    gender = models.CharField(max_length=10)
    relationship = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username}"



class Location(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="location", primary_key=True)
    longitude = models.FloatField(default=0.0)
    latitude = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.user.username}"





class Friend(models.Model):
    sender = models.TextField(max_length=20)
    receiver = models.TextField(max_length=20)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.sender}"

Final-Year-Project-master/helloapp/views.py
from django.dispatch import receiver
from django.shortcuts import render, redirect
from .models import Profile, Location, Friend
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
import math
from django.urls import reverse
from chat.models import Room



# to find the distance brtween to coordinates, gives distance in killometer.
def distance(lat1, lon1, lat2, lon2):
    radius = 6371
    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1) 
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c
    return d






# Create your views here.
def index_view(request):
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    else:
        if request.method == 'POST':
            users = []

            longitude = request.POST["longitude"]
            latitude = request.POST["latitude"]
            if latitude and longitude:
                location = Location.objects.get(user=User.objects.get(username=request.user.username))
                location.latitude = latitude
                location.longitude = longitude
                location.save()

                others = Location.objects.exclude(user = User.objects.get(username=request.user.username))

                for other in others:
                    print ( f"{other.longitude} and {other.latitude} and {other.user.username}")
                    if (not other.user.username == "admin"):
                        lat1 = float(latitude)
                        lat2 = float(other.latitude)
                        lon1 = float(longitude)
                        lon2 = float(other.longitude)

                        p = distance(lat1, lon1, lat2, lon2)
                        print (f"the current distance is : {p} kilometers")
                        # give me all the people who are in the distance of 100 meters
                        if p < 0.3:
                            users.append(other.user.username)
                            print (f"all the people near you are : {users}")

                return render(request, "helloapp/index.html",
                    {   
                    "peoples" : users,
                    }
                )
            else:
                return HttpResponseRedirect(reverse("authentications:login"))
        else:
            request_list = []
            friend_requests = Friend.objects.filter(receiver=request.user.username)
            for requests in friend_requests:
                request_list.append(str(requests))
            
            return render(request, "helloapp/index.html", {"friend_request" : request_list})










def profile_view(request):
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    
    if request.method == 'POST':
        user = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(user=User.objects.get(username=request.user.username))

        if not request.user.first_name == request.POST['first_name']:
            user.first_name = request.POST['first_name']

        if not request.user.last_name == request.POST['last_name']:
            user.last_name = request.POST['last_name']

        if not request.user.username == request.POST['username']:
            if not User.objects.filter(username = request.POST['username']).exists():
                user.username = request.POST['username']
            else:
                return render(request, "helloapp/profile.html", {"message" : f"{request.POST['username']} is already taken!"})

        if not request.user.email == request.POST['email']:
            if not User.objects.filter(email=request.POST['email']).exists():
                user.email = request.POST['email']
            else:
                return render(request, "helloapp/profile.html", {"message" : f"{request.POST['email']} is already taken!"})

        if not profile.bio == request.POST['bio']:
            profile.bio = request.POST['bio']

        if not profile.gender == request.POST['gender']:
            profile.gender = request.POST['gender']

        if not profile.relationship == request.POST['relationship']:
            profile.relationship = request.POST['relationship']
        
        if request.FILES:
            profile.profile_picture = request.FILES['profile_picture']

        user.save()
        profile.save()
        return redirect('helloapp:index')
    else:
        return render(request, "helloapp/profile.html")







def user_details_view(request, username):
    if not request.user.is_authenticated:
        return redirect('authentications:login')

    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)


    if request.method == 'POST':
        sender = request.POST['sender']
        receiver = request.POST['receiver']
        
        if not Friend.objects.filter(sender=sender, receiver=receiver).exists():

            p1 = Location.objects.get(user = User.objects.get(username=sender))
            p2 = Location.objects.get(user = User.objects.get(username=receiver))
            lat1 = p1.latitude
            lat2 = p2.latitude
            lon1 = p1.longitude
            lon2 = p2.longitude

            d = distance(lat1, lon1, lat2, lon2)
            
            if d < 0.3:
                friend = Friend()
                friend.sender = sender
                friend.receiver = receiver
                friend.save()
        
        room_name = str(sender+receiver)
        
        if not Room.objects.filter(name=room_name).exists():
            room = Room()
            room.name = room_name
            room.save()
        


    return render(request, "helloapp/user_details.html", 
        {
            "profile_picture" : profile.profile_picture,
            "profile_bio" : profile.bio,
            "profile_gender" : profile.gender,
            "profile_relationship" : profile.relationship,
            "user_first_name" : user.first_name,
            "user_last_name" : user.last_name,
            "username" : user.username,
        }
    )

helloapp/views.py
from django.dispatch import receiver
from django.shortcuts import render, redirect
from .models import Profile, Location, Friend
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect
import math
from django.urls import reverse
from chat.models import Room



# to find the distance brtween to coordinates, gives distance in killometer.
def distance(lat1, lon1, lat2, lon2):
    radius = 6371
    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1) 
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c
    return d






# Create your views here.
def index_view(request):
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    else:
        if request.method == 'POST':
            users = []

            longitude = request.POST["longitude"]
            latitude = request.POST["latitude"]
            if latitude and longitude:
                location = Location.objects.get(user=User.objects.get(username=request.user.username))
                location.latitude = latitude
                location.longitude = longitude
                location.save()

                others = Location.objects.exclude(user = User.objects.get(username=request.user.username))

                for other in others:
                    print ( f"{other.longitude} and {other.latitude} and {other.user.username}")
                    if (not other.user.username == "admin"):
                        lat1 = float(latitude)
                        lat2 = float(other.latitude)
                        lon1 = float(longitude)
                        lon2 = float(other.longitude)

                        p = distance(lat1, lon1, lat2, lon2)
                        print (f"the current distance is : {p} kilometers")
                        # give me all the people who are in the distance of 100 meters
                        if p < 0.3:
                            users.append(other.user.username)
                            print (f"all the people near you are : {users}")

                return render(request, "helloapp/index.html",
                    {   
                    "peoples" : users,
                    }
                )
            else:
                return HttpResponseRedirect(reverse("authentications:login"))
        else:
            request_list = []
            friend_requests = Friend.objects.filter(receiver=request.user.username)
            for requests in friend_requests:
                request_list.append(str(requests))
            
            return render(request, "helloapp/index.html", {"friend_request" : request_list})










def profile_view(request):
    if not request.user.is_authenticated:
        return redirect('authentications:login')
    
    if request.method == 'POST':
        user = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(user=User.objects.get(username=request.user.username))

        if not request.user.first_name == request.POST['first_name']:
            user.first_name = request.POST['first_name']

        if not request.user.last_name == request.POST['last_name']:
            user.last_name = request.POST['last_name']

        if not request.user.username == request.POST['username']:
            if not User.objects.filter(username = request.POST['username']).exists():
                user.username = request.POST['username']
            else:
                return render(request, "helloapp/profile.html", {"message" : f"{request.POST['username']} is already taken!"})

        if not request.user.email == request.POST['email']:
            if not User.objects.filter(email=request.POST['email']).exists():
                user.email = request.POST['email']
            else:
                return render(request, "helloapp/profile.html", {"message" : f"{request.POST['email']} is already taken!"})

        if not profile.bio == request.POST['bio']:
            profile.bio = request.POST['bio']

        if not profile.gender == request.POST['gender']:
            profile.gender = request.POST['gender']

        if not profile.relationship == request.POST['relationship']:
            profile.relationship = request.POST['relationship']
        
        if request.FILES:
            profile.profile_picture = request.FILES['profile_picture']

        user.save()
        profile.save()
        return redirect('helloapp:index')
    else:
        return render(request, "helloapp/profile.html")







def user_details_view(request, username):
    if not request.user.is_authenticated:
        return redirect('authentications:login')

    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)


    if request.method == 'POST':
        sender = request.POST['sender']
        receiver = request.POST['receiver']
        
        if not Friend.objects.filter(sender=sender, receiver=receiver).exists():

            p1 = Location.objects.get(user = User.objects.get(username=sender))
            p2 = Location.objects.get(user = User.objects.get(username=receiver))
            lat1 = p1.latitude
            lat2 = p2.latitude
            lon1 = p1.longitude
            lon2 = p2.longitude

            d = distance(lat1, lon1, lat2, lon2)
            
            if d < 0.3:
                friend = Friend()
                friend.sender = sender
                friend.receiver = receiver
                friend.save()
        
        room_name = str(sender+receiver)
        
        if not Room.objects.filter(name=room_name).exists():
            room = Room()
            room.name = room_name
            room.save()
        


    return render(request, "helloapp/user_details.html", 
        {
            "profile_picture" : profile.profile_picture,
            "profile_bio" : profile.bio,
            "profile_gender" : profile.gender,
            "profile_relationship" : profile.relationship,
            "user_first_name" : user.first_name,
            "user_last_name" : user.last_name,
            "username" : user.username,
        }
    )

Final-Year-Project-master/helloapp/templates/helloapp/index.html
{% extends "helloapp/layout.html" %}
{% load static %}

{% block title %}{{request.user.first_name}} {{request.user.last_name}} ⦁ looknearby{% endblock %}

{% block body %} 



    <!-- FOR STYLE -->
    <!-- this is the navigation bar -->
    <div id="nav">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <div style="margin-top: 20px; margin-bottom: 20px;">
                    <h1 class="display-6" style="text-align: center;" id="title">looknearby</h1>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="position:absolute; right: 0px;">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url "helloapp:index" %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url "helloapp:profile" %}">Edit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "authentications:logout" %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>





    <!-- FOR STYLE -->
    <!-- if anybody sends you friend request then this div is for that -->

    <div>

        {% if friend_request %}
            <ul>
            {% for friend in friend_request %}
                
                {% with friend|add:request.user.username as name %} 
                    <li><a href="{% url "helloapp:user_details" friend %}">{{ friend }}</a> is asking you to chat. <a href="{% url "chat:room" name %}">let's chat</a></li>
                {% endwith %}

            {% endfor %}
            </ul>
        {% endif %}

    </div>



    <div class='cont'>
    <!-- FOR STYLE -->
    <!-- this is for showing your profile picture and your name -->
    <!-- DO NOT CHANGE THE ID -->
    <div id="profile-background">

        <div class="flex-container">
            
                {% if request.user.profile.first.profile_picture %}
                    <img class="profile-picture" src="{{request.user.profile.first.profile_picture.url}}" alt="Image Not Found!" >
                {% else %}
                    <img class="profile-picture" src="{% static "helloapp/default_profile_picture.png" %}" alt="Image Not Found!" >
                {% endif %}
            

            
                <h2 id="user-name">{{request.user.first_name}} {{request.user.last_name}}</h2>
            
        </div>

    </div>





    <!-- FOR STYLE -->
    <!-- this is for showing your profile details -->
    <!-- DO NOT CHANGE THE ID -->
  


    <div id="profile-bio">
        <h3> profile About...</h3>
        <ul id="current-user-info">
            {% if request.user.profile.first.bio %}
                <li>{{request.user.profile.first.bio}}</li>
            {% endif %}
    
            <li>{{request.user.first_name}} {{request.user.last_name}}</li>
    
            <li>{{request.user.username}}</li>
    
            {% if request.user.profile.first.gender %}
                <li>{{request.user.profile.first.gender}}</li>
            {% endif %}
    
            {% if request.user.profile.first.relationship %}
                <li>{{request.user.profile.first.relationship}}</li>
            {% endif %}
        </ul>
    </div>

    




    <!-- FOR STYLE -->
    <!-- these are three buttons to get, send your current location and button to show other people list -->
    <!-- DO NOT CHANGE THE ID -->
    <div id="profile-buttons">
        <!-- 1st button to get user's current location -->
        <button id="get-location">get my location</button>

        <!-- this is the form to send user's current location to djago database -->
        <form id="my-form" method="post" action="{% url "helloapp:index" %}">
            {% csrf_token %}
            <input type="text" name="latitude" id="lat" value="0" hidden>
            <input type="text" name="longitude" id="lon" value="0" hidden>
            <input type="submit" value="send your current location" id="send-your-current-location">
        </form>

        <!-- 3rd button to show nearby user's username and links to see about themselfs -->
        <button id="show-people">Show people near you.</button>

    </div>










    <!-- FOR STYLE -->
    <!-- this is a list that will show all the others people who are near you! -->
    <!-- DO NOT CHANGE THE ID -->
    <div id="other-people-list">
        <!-- this is the list of all possible users -->
        <ul id="people-list" style="display: none;"> 
            {% for people in peoples %} 
                <li><a href="{% url "helloapp:user_details" people %}">{{ people }}</a></li>
            {% empty %}
                <li>No one arround you</li>
        {% endfor %}
        </ul>
    </div>
</div>
    





    <!-- do not change this script tag -->

    <script>
        let form=document.querySelector('#my-form');
        form.addEventListener('submit',()=>{event.preventDefault();})

        document.querySelector('#get-location').onclick = function() {
            if ( 'geolocation' in navigator ) {
                console.log ("Geolocation is supported!");

                navigator.geolocation.getCurrentPosition((position) => {
                    document.querySelector('#lat').value = position.coords.latitude;
                    document.querySelector('#lon').value = position.coords.longitude;
                });

            }
            else {
                console.log ("Geolocation is not supported!");
            }
        }



        document.querySelector('#show-people').onclick = function() {
            document.querySelector('#people-list').style.display = "block";
        }

        let glc=document.querySelector('#get-location');
let sl=document.querySelector('#send-your-current-location');
let sa=document.querySelector('#show-people');
let time=()=>{
    setTimeout(()=>{
        sl.style.display='inline';
    },1000)
}
let time1=()=>{
    setTimeout(()=>{
        sa.style.display='inline';
    },1000)
}
glc.addEventListener('click',time);
sl.addEventListener('click',time1);
    </script>

{% endblock %}

Final-Year-Project-master/helloapp/templates/helloapp/layout.html
{% load static %}

<!-- THIS IS LAYOUT FILE. DON'T NEED TO STYLE. IF YOU ARE USING CSS OR BOOTSTRAP OR JAVASCRIPT THEN IMPORT ALL THE LINKS HERE -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} {% endblock %}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   
     <link rel="stylesheet" href="{% static "helloapp/style.css" %}">
    </head>

<body>
    
    {% block body %} {% endblock %}
</body>
</html>

Final-Year-Project-master/helloapp/templates/helloapp/profile.html
{% extends "helloapp/layout.html" %}
{% load static %}
{% block title %} Edit Profile ⦁ looknearby{% endblock %}


{% block body %} 
    {% if message %} 
        {{message}}
    {% endif %}



    <!-- FOR STYLE -->
    <!-- this is the naviagtion bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <div style="margin-top: 20px; margin-bottom: 20px;">
                    <h1 class="display-6" style="text-align: center;" id="title">looknearby</h1>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="position:absolute; right: 0px;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "helloapp:index" %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "helloapp:profile" %}">Edit</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "authentications:logout" %}">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>





    <!-- this is the form that is for changing the profile details -->
    <!-- FOR STYLE -->
    <form action="{% url "helloapp:profile" %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% if request.user.profile.first.profile_picture %}
            <img src="{{request.user.profile.first.profile_picture.url}}" alt="Not selected" style="width:200px">
        {% else %}
            <img src="{% static "helloapp/default_profile_picture.png" %}" alt="Not Found!" style="width:200px">
        {% endif %}
        <label for="profile_picture">upload a new profile picture</label>
        <input type="file" name="profile_picture">

        <label for="first_name">First Name </label>
        <input type="text" name="first_name" value="{{request.user.first_name}}" placeholder="First Name">

        <label for="last_name">Last Name </label>
        <input type="text" name="last_name" value="{{request.user.last_name}}" placeholder="Last Name">

        <label for="username">Username </label>
        <input type="text" name="username" value="{{request.user.username}}" placeholder="Username">

        <label for="bio">Bio </label>
        <textarea name="bio" cols="40" rows="4" >{{request.user.profile.first.bio}}</textarea>

        <label for="gender">Gender </label>
        <select name="gender">
            <option value="{{request.user.profile.first.gender}}" selected>{{request.user.profile.first.gender}}(selected)</option>
            <option value="female">Female</option>
            <option value="male">Male</option>
            <option value="others">Others</option>
            <option value="prefer not to say">Prefer not to say</option>
        </select>

        <label for="relationship">Relationship Status </label>
        <select name="relationship">
            <option value="{{request.user.profile.first.relationship}}">{{request.user.profile.first.relationship}}(selected)</option>
            <option value="single">Single</option>
            <option value="in a relationship">In a relationship</option>
            <option value="married">Married</option>
            <option value="complecated">Complecated</option>
            <option value="not intrested">Not intrested</option>
        </select>

        <label for="email">Email </label>
        <input type="text" name="email" value="{{request.user.email}}" placeholder="Email id">

        <input type="submit" value="submit">
    </form>

    <!-- FOR STYLE -->
    <!-- this is the button to cancel the editing -->
    ...
    <a href="{% url "helloapp:index" %}"><button>cancel</button></a>
{% endblock %}

Final-Year-Project-master/helloapp/templates/helloapp/user_details.html
{% extends "helloapp/layout.html" %}
{% load static %}
{% block title %} {% endblock %}
{% block body %}
    
    <!-- this is for showing the profile picture -->
    <!-- FOR STYLE -->
    {% if profile_picture %}
    <img src="{{profile_picture.url}}" alt="Image Not Found!" style="width:200px">
    {% else %}
    <img src="{% static "helloapp/default_profile_picture.png" %}" alt="Image Not Found!" style="width:200px">
    {% endif %}

    <!-- this is for shwing the user details -->
    <!-- FOR STYLE -->
    <ul>
        {% if profile_bio %}
            <li>{{profile_bio}}</li>
        {% endif %}

        <li>{{user_first_name}} {{user_last_name}}</li>

        {% if profile_gender %}
            <li>{{profile_gender}}</li>
        {% endif %}

        {% if profile_relationship %}
            <li>{{profile_relationship}}</li>
        {% endif %}
    </ul>





    <!-- this is for if you want to chat with the person -->
    <!-- FOR STYLE -->
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="sender" value="{{ request.user.username }}" hidden>
            <input type="text" name="receiver" value="{{ username }}" hidden>
            <input type="submit" value="ask to chat">
        </form>
    </div>


    <!-- this is a link to chat with persion -->
    <!-- FOR STYLE -->
    {% with request.user.username|add:username as name %}
        <a href="{% url "chat:room" name  %}">let's chat</a>
    {% endwith %}
    
{% endblock %}